# Workflow for deploying a Flask app to an EC2 instance using GitHub Actions
name: CI
on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Setup SSH key and permissions
      - name: Configure SSH Key
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 400 private_key.pem

      # Create .env file from GitHub Secrets
      - name: Generate .env File
        run: |
          cat <<EOF > .env
          APP_NAME=${{ secrets.APP_NAME || '' }}
          EOF
      - name: Make app dir and Copy .env 
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_IP << 'EOF'
            if [ ! -d "$HOME/app" ];then
              mkdir $HOME/app
            fi
          EOF
          scp -o StrictHostKeyChecking=no -i private_key.pem .env $EC2_USER@$EC2_IP:~/app/.env
      
      # Deploy application to EC2
      - name: Clone the Repo and install dependencies
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_IP << 'EOF'
            sudo yum install -y git python3 pip
            APP_DIR="$HOME/app"
            REPO_URL="https://github.com/satyamtechstax/fastapi-cicd.git"
            if [ -d "$APP_DIR/.git" ];then
                cd $APP_DIR
                git pull $REPO_URL 
                echo "repo exist"
                sudo bash restart.sh
            else
                cp -r $APP_DIR $APP_DIR.tmp
                rm -rf $APP_DIR
                echo "Repo not exist" $APP_DIR
                git clone $REPO_URL $APP_DIR
                cd $APP_DIR
                cp $APP_DIR.tmp/.env $APP_DIR
                rm -rf $APP_DIR.tmp
                sudo bash install.sh
            fi
          EOF
      # Cleanup SSH key
      - name: Cleanup
        run: rm -f private_key.pem .env
